import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import {Outfit} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Liqo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${outfit.className} font-sans`}
    >
      <body className="min-h-full flex flex-col pt-10 relative pb-30">
        <Navbar />
        {children}</body>
    </html>
  );
}
